module.exports = {
  structures: {
    STRUCTURE_CONTAINER: "container",
    STRUCTURE_CONTROLLER: "controller",
    STRUCTURE_EXTENSION: "extension",
    STRUCTURE_EXTRACTOR: "extractor",
    STRUCTURE_FACTORY: "factory",
    STRUCTURE_INADER_CORE: "invaderCore",
    STRUCTURE_KEEPER_LAIR: "keeperLair",
    STRUCTURE_LAB: "lab",
    STRUCTURE_LINK: "link",
    STRUCTURE_NUKER: "nuker",
    STRUCTURE_OBSERVER: "observer",
    STRUCTURE_PORTAL: "portal",
    STRUCTURE_POWER_BANK: "powerBank",
    STRUCTURE_POWER_SPAWN: "powerSpawn",
    STRUCTURE_RAMPART: "rampart",
    STRUCTURE_ROAD: "road",
    STRUCTURE_SPAWN: "spawn",
    STRUCTURE_STORAGE: "storage",
    STRUCTURE_TERMINAL: "terminal",
    STRUCTURE_TOWER: "tower",
    STRUCTURE_WALL: "constructedWall",
  },
  partCosts: {
    TOUGH: 10,
    MOVE: 50,
    WORK: 100,
    CARRY: 50,
    ATTACK: 80,
    RANGED_ATTACK: 150,
    HEAL: 250,
    CLAIM: 600,
  },
  roles: {
    HARVESTER: "harvester",
    HAULER: "hauler",
    BUILDER: "builder",
    UPGRADER: "upgrader",
    SURVEYOR: "surveyor",
  },
};
